/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 02:32:48 PM MEZ 
//


package at.medevit.elexis.at.rezepte.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PatientName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PatientVersicherungsnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PatientAnschrift" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Verschreibungen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Verschreibung" type="{http://www.medevit.at/RezeptAT}Verschreibung" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="bgimg" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patientName",
    "patientVersicherungsnummer",
    "patientAnschrift",
    "datum",
    "verschreibungen"
})
@XmlRootElement(name = "RezeptAT")
public class RezeptAT {

    @XmlElement(name = "PatientName", required = true)
    protected String patientName;
    @XmlElement(name = "PatientVersicherungsnummer", required = true)
    protected String patientVersicherungsnummer;
    @XmlElement(name = "PatientAnschrift", required = true)
    protected String patientAnschrift;
    @XmlElement(name = "Datum", required = true)
    protected String datum;
    @XmlElement(name = "Verschreibungen", required = true)
    protected RezeptAT.Verschreibungen verschreibungen;
    @XmlAttribute
    protected String bgimg;

    /**
     * Gets the value of the patientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * Sets the value of the patientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientName(String value) {
        this.patientName = value;
    }

    /**
     * Gets the value of the patientVersicherungsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientVersicherungsnummer() {
        return patientVersicherungsnummer;
    }

    /**
     * Sets the value of the patientVersicherungsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientVersicherungsnummer(String value) {
        this.patientVersicherungsnummer = value;
    }

    /**
     * Gets the value of the patientAnschrift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientAnschrift() {
        return patientAnschrift;
    }

    /**
     * Sets the value of the patientAnschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientAnschrift(String value) {
        this.patientAnschrift = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the verschreibungen property.
     * 
     * @return
     *     possible object is
     *     {@link RezeptAT.Verschreibungen }
     *     
     */
    public RezeptAT.Verschreibungen getVerschreibungen() {
    	if (verschreibungen == null) {
            verschreibungen = new RezeptAT.Verschreibungen();
        }
    	return verschreibungen;
    }

    /**
     * Sets the value of the verschreibungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link RezeptAT.Verschreibungen }
     *     
     */
    public void setVerschreibungen(RezeptAT.Verschreibungen value) {
        this.verschreibungen = value;
    }

    /**
     * Gets the value of the bgimg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgimg() {
        return bgimg;
    }

    /**
     * Sets the value of the bgimg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgimg(String value) {
        this.bgimg = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Verschreibung" type="{http://www.medevit.at/RezeptAT}Verschreibung" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "verschreibung"
    })
    public static class Verschreibungen {

        @XmlElement(name = "Verschreibung", required = true)
        protected List<Verschreibung> verschreibung;

        /**
         * Gets the value of the verschreibung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the verschreibung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVerschreibung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Verschreibung }
         * 
         * 
         */
        public List<Verschreibung> getVerschreibung() {
            if (verschreibung == null) {
                verschreibung = new ArrayList<Verschreibung>();
            }
            return this.verschreibung;
        }

    }

}
