/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 05:14:13 PM MESZ 
//


package at.medevit.elexis.at.rezepte.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import ch.elexis.data.Prescription;


/**
 * <p>Java class for Verschreibung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Verschreibung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Artikelname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Einnahmevorschrift" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Dosierung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Originalpackung" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Bemerkung" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Verschreibung", propOrder = {
    "artikelname",
    "einnahmevorschrift",
    "dosierung",
    "originalpackung",
    "bemerkung"
})
public class Verschreibung {

    @XmlElement(name = "Artikelname", required = true)
    protected String artikelname;
    @XmlElement(name = "Einnahmevorschrift")
    protected String einnahmevorschrift;
    @XmlElement(name = "Dosierung", required = true)
    protected String dosierung;
    @XmlElement(name = "Originalpackung")
    protected String originalpackung;
    @XmlElement(name = "Bemerkung")
    protected String bemerkung;
    @XmlTransient
    protected Prescription prescription;

    /**
     * Gets the value of the artikelname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtikelname() {
        return artikelname;
    }

    /**
     * Sets the value of the artikelname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtikelname(String value) {
        this.artikelname = value;
    }

    /**
     * Gets the value of the einnahmevorschrift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEinnahmevorschrift() {
        return einnahmevorschrift;
    }

    /**
     * Sets the value of the einnahmevorschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEinnahmevorschrift(String value) {
        this.einnahmevorschrift = value;
    }

    /**
     * Gets the value of the dosierung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDosierung() {
        return dosierung;
    }

    /**
     * Sets the value of the dosierung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDosierung(String value) {
        this.dosierung = value;
    }

    /**
     * Gets the value of the originalpackung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalpackung() {
        return originalpackung;
    }

    /**
     * Sets the value of the originalpackung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalpackung(String value) {
        this.originalpackung = value;
    }

    /**
     * Gets the value of the bemerkung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBemerkung() {
        return bemerkung;
    }

    /**
     * Sets the value of the bemerkung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBemerkung(String value) {
        this.bemerkung = value;
    }

	public void setPrescription(Prescription prescription) {
		this.prescription = prescription;
	}

	public Prescription getPrescription() {
		return prescription;
	}

}
