/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AufenthaltsArtCode"/>
 *         &lt;element ref="{}AufenthaltsArtBezeichnung" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aufenthaltsArtCode",
    "aufenthaltsArtBezeichnung"
})
@XmlRootElement(name = "AufenthaltsArt")
public class AufenthaltsArt {

    @XmlElement(name = "AufenthaltsArtCode", required = true)
    protected String aufenthaltsArtCode;
    @XmlElement(name = "AufenthaltsArtBezeichnung")
    protected String aufenthaltsArtBezeichnung;

    /**
     * Gets the value of the aufenthaltsArtCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAufenthaltsArtCode() {
        return aufenthaltsArtCode;
    }

    /**
     * Sets the value of the aufenthaltsArtCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAufenthaltsArtCode(String value) {
        this.aufenthaltsArtCode = value;
    }

    /**
     * Gets the value of the aufenthaltsArtBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAufenthaltsArtBezeichnung() {
        return aufenthaltsArtBezeichnung;
    }

    /**
     * Sets the value of the aufenthaltsArtBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAufenthaltsArtBezeichnung(String value) {
        this.aufenthaltsArtBezeichnung = value;
    }

}
