/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DokumentArt"/>
 *         &lt;element ref="{}DokumentArtBezeichnung"/>
 *         &lt;element ref="{}DokumentNummer" minOccurs="0"/>
 *         &lt;element ref="{}DateiName" minOccurs="0"/>
 *         &lt;element ref="{}DateiArt" minOccurs="0"/>
 *         &lt;element ref="{}Kommunikation" minOccurs="0"/>
 *         &lt;element ref="{}MedienArt"/>
 *         &lt;element ref="{}SchemaIdentifikation" minOccurs="0"/>
 *         &lt;element ref="{}FreiText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dokumentArt",
    "dokumentArtBezeichnung",
    "dokumentNummer",
    "dateiName",
    "dateiArt",
    "kommunikation",
    "medienArt",
    "schemaIdentifikation",
    "freiText"
})
@XmlRootElement(name = "DokumentenBeilage")
public class DokumentenBeilage {

    @XmlElement(name = "DokumentArt", required = true)
    protected String dokumentArt;
    @XmlElement(name = "DokumentArtBezeichnung", required = true)
    protected String dokumentArtBezeichnung;
    @XmlElement(name = "DokumentNummer")
    protected String dokumentNummer;
    @XmlElement(name = "DateiName")
    protected String dateiName;
    @XmlElement(name = "DateiArt")
    protected String dateiArt;
    @XmlElement(name = "Kommunikation")
    protected Kommunikation kommunikation;
    @XmlElement(name = "MedienArt", required = true)
    protected String medienArt;
    @XmlElement(name = "SchemaIdentifikation")
    protected String schemaIdentifikation;
    @XmlElement(name = "FreiText")
    protected String freiText;

    /**
     * Gets the value of the dokumentArt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentArt() {
        return dokumentArt;
    }

    /**
     * Sets the value of the dokumentArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentArt(String value) {
        this.dokumentArt = value;
    }

    /**
     * Gets the value of the dokumentArtBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentArtBezeichnung() {
        return dokumentArtBezeichnung;
    }

    /**
     * Sets the value of the dokumentArtBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentArtBezeichnung(String value) {
        this.dokumentArtBezeichnung = value;
    }

    /**
     * Gets the value of the dokumentNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentNummer() {
        return dokumentNummer;
    }

    /**
     * Sets the value of the dokumentNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentNummer(String value) {
        this.dokumentNummer = value;
    }

    /**
     * Gets the value of the dateiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateiName() {
        return dateiName;
    }

    /**
     * Sets the value of the dateiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateiName(String value) {
        this.dateiName = value;
    }

    /**
     * Gets the value of the dateiArt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateiArt() {
        return dateiArt;
    }

    /**
     * Sets the value of the dateiArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateiArt(String value) {
        this.dateiArt = value;
    }

    /**
     * Gets the value of the kommunikation property.
     * 
     * @return
     *     possible object is
     *     {@link Kommunikation }
     *     
     */
    public Kommunikation getKommunikation() {
        return kommunikation;
    }

    /**
     * Sets the value of the kommunikation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kommunikation }
     *     
     */
    public void setKommunikation(Kommunikation value) {
        this.kommunikation = value;
    }

    /**
     * Gets the value of the medienArt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedienArt() {
        return medienArt;
    }

    /**
     * Sets the value of the medienArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedienArt(String value) {
        this.medienArt = value;
    }

    /**
     * Gets the value of the schemaIdentifikation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaIdentifikation() {
        return schemaIdentifikation;
    }

    /**
     * Sets the value of the schemaIdentifikation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaIdentifikation(String value) {
        this.schemaIdentifikation = value;
    }

    /**
     * Gets the value of the freiText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreiText() {
        return freiText;
    }

    /**
     * Sets the value of the freiText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreiText(String value) {
        this.freiText = value;
    }

}
