/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EingriffsNummerKomplett"/>
 *         &lt;element ref="{}EingriffsBezeichnung"/>
 *         &lt;element ref="{}EingriffsCode" minOccurs="0"/>
 *         &lt;element ref="{}OPSchemaBezeichnung" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eingriffsNummerKomplett",
    "eingriffsBezeichnung",
    "eingriffsCode",
    "opSchemaBezeichnung"
})
@XmlRootElement(name = "EingriffsInformationen")
public class EingriffsInformationen {

    @XmlElement(name = "EingriffsNummerKomplett", required = true)
    protected String eingriffsNummerKomplett;
    @XmlElement(name = "EingriffsBezeichnung", required = true)
    protected String eingriffsBezeichnung;
    @XmlElement(name = "EingriffsCode")
    protected String eingriffsCode;
    @XmlElement(name = "OPSchemaBezeichnung")
    protected String opSchemaBezeichnung;

    /**
     * Gets the value of the eingriffsNummerKomplett property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEingriffsNummerKomplett() {
        return eingriffsNummerKomplett;
    }

    /**
     * Sets the value of the eingriffsNummerKomplett property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEingriffsNummerKomplett(String value) {
        this.eingriffsNummerKomplett = value;
    }

    /**
     * Gets the value of the eingriffsBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEingriffsBezeichnung() {
        return eingriffsBezeichnung;
    }

    /**
     * Sets the value of the eingriffsBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEingriffsBezeichnung(String value) {
        this.eingriffsBezeichnung = value;
    }

    /**
     * Gets the value of the eingriffsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEingriffsCode() {
        return eingriffsCode;
    }

    /**
     * Sets the value of the eingriffsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEingriffsCode(String value) {
        this.eingriffsCode = value;
    }

    /**
     * Gets the value of the opSchemaBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPSchemaBezeichnung() {
        return opSchemaBezeichnung;
    }

    /**
     * Sets the value of the opSchemaBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPSchemaBezeichnung(String value) {
        this.opSchemaBezeichnung = value;
    }

}
