/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}RollenArt"/>
 *         &lt;element ref="{}BetriebsStelleKey"/>
 *         &lt;element ref="{}GesamterName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rollenArt",
    "betriebsStelleKey",
    "gesamterName"
})
@XmlRootElement(name = "KostentraegerSozialVersicherung")
public class KostentraegerSozialVersicherung {

    @XmlElement(name = "RollenArt", required = true)
    protected RollenArt rollenArt;
    @XmlElement(name = "BetriebsStelleKey", required = true)
    protected String betriebsStelleKey;
    @XmlElement(name = "GesamterName", required = true)
    protected String gesamterName;

    /**
     * Gets the value of the rollenArt property.
     * 
     * @return
     *     possible object is
     *     {@link RollenArt }
     *     
     */
    public RollenArt getRollenArt() {
        return rollenArt;
    }

    /**
     * Sets the value of the rollenArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RollenArt }
     *     
     */
    public void setRollenArt(RollenArt value) {
        this.rollenArt = value;
    }

    /**
     * Hier wird im Gegensatz zu allen anderen BetriebsStelleKey-Elementen in den Nachrichten kein Betriebsstellenkey angegeben, sondern nur der Eintrag aus der Codeliste D05 f�r die zahlungspflichtige Sozialversicherung als Kostentr�ger (Wertangabe immer 2-stellig), zB. "17" f�r die Salzburger Gebietskrankenkasse.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBetriebsStelleKey() {
        return betriebsStelleKey;
    }

    /**
     * Sets the value of the betriebsStelleKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBetriebsStelleKey(String value) {
        this.betriebsStelleKey = value;
    }

    /**
     * der Sozialversicherung
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGesamterName() {
        return gesamterName;
    }

    /**
     * Sets the value of the gesamterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGesamterName(String value) {
        this.gesamterName = value;
    }

}
