/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NebenBedingungsCode"/>
 *         &lt;element ref="{}NebenBedingungsBezeichnung"/>
 *         &lt;element ref="{}NebenBedingungsWert"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nebenBedingungsCode",
    "nebenBedingungsBezeichnung",
    "nebenBedingungsWert"
})
@XmlRootElement(name = "NebenBedingungen")
public class NebenBedingungen {

    @XmlElement(name = "NebenBedingungsCode", required = true)
    protected String nebenBedingungsCode;
    @XmlElement(name = "NebenBedingungsBezeichnung", required = true)
    protected String nebenBedingungsBezeichnung;
    @XmlElement(name = "NebenBedingungsWert", required = true)
    protected BigDecimal nebenBedingungsWert;

    /**
     * Gets the value of the nebenBedingungsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNebenBedingungsCode() {
        return nebenBedingungsCode;
    }

    /**
     * Sets the value of the nebenBedingungsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNebenBedingungsCode(String value) {
        this.nebenBedingungsCode = value;
    }

    /**
     * Gets the value of the nebenBedingungsBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNebenBedingungsBezeichnung() {
        return nebenBedingungsBezeichnung;
    }

    /**
     * Sets the value of the nebenBedingungsBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNebenBedingungsBezeichnung(String value) {
        this.nebenBedingungsBezeichnung = value;
    }

    /**
     * Gets the value of the nebenBedingungsWert property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNebenBedingungsWert() {
        return nebenBedingungsWert;
    }

    /**
     * Sets the value of the nebenBedingungsWert property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNebenBedingungsWert(BigDecimal value) {
        this.nebenBedingungsWert = value;
    }

}
