/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}RechnungsNummer"/>
 *         &lt;element ref="{}RechnungsDatum"/>
 *         &lt;element ref="{}FreiText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rechnungsNummer",
    "rechnungsDatum",
    "freiText"
})
@XmlRootElement(name = "ReferenzAufRechnung")
public class ReferenzAufRechnung {

    @XmlElement(name = "RechnungsNummer", required = true)
    protected String rechnungsNummer;
    @XmlElement(name = "RechnungsDatum", required = true)
    protected String rechnungsDatum;
    @XmlElement(name = "FreiText")
    protected String freiText;

    /**
     * Gets the value of the rechnungsNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRechnungsNummer() {
        return rechnungsNummer;
    }

    /**
     * Sets the value of the rechnungsNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRechnungsNummer(String value) {
        this.rechnungsNummer = value;
    }

    /**
     * Gets the value of the rechnungsDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRechnungsDatum() {
        return rechnungsDatum;
    }

    /**
     * Sets the value of the rechnungsDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRechnungsDatum(String value) {
        this.rechnungsDatum = value;
    }

    /**
     * hier: Kommentar oder Erkl�rung zu der referenzierten Rechnung
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreiText() {
        return freiText;
    }

    /**
     * Sets the value of the freiText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreiText(String value) {
        this.freiText = value;
    }

}
