/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NachrichtenArt"/>
 *         &lt;element ref="{}NachrichtenArtBezeichnung"/>
 *         &lt;element ref="{}NachrichtenNummer"/>
 *         &lt;element ref="{}NachrichtenDatum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenArt",
    "nachrichtenArtBezeichnung",
    "nachrichtenNummer",
    "nachrichtenDatum"
})
@XmlRootElement(name = "ReferenzAufNachricht")
public class ReferenzAufNachricht {

    @XmlElement(name = "NachrichtenArt", required = true)
    protected String nachrichtenArt;
    @XmlElement(name = "NachrichtenArtBezeichnung", required = true)
    protected String nachrichtenArtBezeichnung;
    @XmlElement(name = "NachrichtenNummer", required = true)
    protected String nachrichtenNummer;
    @XmlElement(name = "NachrichtenDatum", required = true)
    protected String nachrichtenDatum;

    /**
     * Gets the value of the nachrichtenArt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNachrichtenArt() {
        return nachrichtenArt;
    }

    /**
     * Sets the value of the nachrichtenArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNachrichtenArt(String value) {
        this.nachrichtenArt = value;
    }

    /**
     * Gets the value of the nachrichtenArtBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNachrichtenArtBezeichnung() {
        return nachrichtenArtBezeichnung;
    }

    /**
     * Sets the value of the nachrichtenArtBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNachrichtenArtBezeichnung(String value) {
        this.nachrichtenArtBezeichnung = value;
    }

    /**
     * Gets the value of the nachrichtenNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNachrichtenNummer() {
        return nachrichtenNummer;
    }

    /**
     * Sets the value of the nachrichtenNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNachrichtenNummer(String value) {
        this.nachrichtenNummer = value;
    }

    /**
     * Gets the value of the nachrichtenDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNachrichtenDatum() {
        return nachrichtenDatum;
    }

    /**
     * Sets the value of the nachrichtenDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNachrichtenDatum(String value) {
        this.nachrichtenDatum = value;
    }

}
