/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SpitalsAnmerkungsCode" minOccurs="0"/>
 *         &lt;element ref="{}SpitalsAnmerkungsBezeichnung" minOccurs="0"/>
 *         &lt;element ref="{}FreiText" maxOccurs="9" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spitalsAnmerkungsCode",
    "spitalsAnmerkungsBezeichnung",
    "freiText"
})
@XmlRootElement(name = "SpitalsAnmerkungen")
public class SpitalsAnmerkungen {

    @XmlElement(name = "SpitalsAnmerkungsCode")
    protected String spitalsAnmerkungsCode;
    @XmlElement(name = "SpitalsAnmerkungsBezeichnung")
    protected String spitalsAnmerkungsBezeichnung;
    @XmlElement(name = "FreiText")
    protected List<String> freiText;

    /**
     * Gets the value of the spitalsAnmerkungsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpitalsAnmerkungsCode() {
        return spitalsAnmerkungsCode;
    }

    /**
     * Sets the value of the spitalsAnmerkungsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpitalsAnmerkungsCode(String value) {
        this.spitalsAnmerkungsCode = value;
    }

    /**
     * Gets the value of the spitalsAnmerkungsBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpitalsAnmerkungsBezeichnung() {
        return spitalsAnmerkungsBezeichnung;
    }

    /**
     * Sets the value of the spitalsAnmerkungsBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpitalsAnmerkungsBezeichnung(String value) {
        this.spitalsAnmerkungsBezeichnung = value;
    }

    /**
     * Gets the value of the freiText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freiText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreiText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFreiText() {
        if (freiText == null) {
            freiText = new ArrayList<String>();
        }
        return this.freiText;
    }

}
