/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tpcAdresse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpcAdresse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}AdresseKey" minOccurs="0"/>
 *         &lt;element name="AdresseArt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdresseStruktur" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PostLeitzahl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Strasse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HausNummer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Staat" type="{}tpsNationalityTyp" minOccurs="0"/>
 *         &lt;element name="GesamteAdresse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpcAdresse", propOrder = {

})
public class TpcAdresse {

    @XmlElement(name = "AdresseKey")
    protected String adresseKey;
    @XmlElement(name = "AdresseArt")
    protected String adresseArt;
    @XmlElement(name = "AdresseStruktur")
    protected String adresseStruktur;
    @XmlElement(name = "PostLeitzahl")
    protected String postLeitzahl;
    @XmlElement(name = "Ort")
    protected String ort;
    @XmlElement(name = "Strasse")
    protected String strasse;
    @XmlElement(name = "HausNummer")
    protected String hausNummer;
    @XmlElement(name = "Staat")
    protected String staat;
    @XmlElement(name = "GesamteAdresse")
    protected String gesamteAdresse;

    /**
     * Gets the value of the adresseKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresseKey() {
        return adresseKey;
    }

    /**
     * Sets the value of the adresseKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresseKey(String value) {
        this.adresseKey = value;
    }

    /**
     * Gets the value of the adresseArt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresseArt() {
        return adresseArt;
    }

    /**
     * Sets the value of the adresseArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresseArt(String value) {
        this.adresseArt = value;
    }

    /**
     * Gets the value of the adresseStruktur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresseStruktur() {
        return adresseStruktur;
    }

    /**
     * Sets the value of the adresseStruktur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresseStruktur(String value) {
        this.adresseStruktur = value;
    }

    /**
     * Gets the value of the postLeitzahl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostLeitzahl() {
        return postLeitzahl;
    }

    /**
     * Sets the value of the postLeitzahl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostLeitzahl(String value) {
        this.postLeitzahl = value;
    }

    /**
     * Gets the value of the ort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrt() {
        return ort;
    }

    /**
     * Sets the value of the ort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrt(String value) {
        this.ort = value;
    }

    /**
     * Gets the value of the strasse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrasse() {
        return strasse;
    }

    /**
     * Sets the value of the strasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrasse(String value) {
        this.strasse = value;
    }

    /**
     * Gets the value of the hausNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHausNummer() {
        return hausNummer;
    }

    /**
     * Sets the value of the hausNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHausNummer(String value) {
        this.hausNummer = value;
    }

    /**
     * Gets the value of the staat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaat() {
        return staat;
    }

    /**
     * Sets the value of the staat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaat(String value) {
        this.staat = value;
    }

    /**
     * Gets the value of the gesamteAdresse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGesamteAdresse() {
        return gesamteAdresse;
    }

    /**
     * Sets the value of the gesamteAdresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGesamteAdresse(String value) {
        this.gesamteAdresse = value;
    }

}
