/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for tpcAufenthalt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpcAufenthalt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}AufenthaltsKey"/>
 *         &lt;element ref="{}BetriebsStelleKey" minOccurs="0"/>
 *         &lt;element ref="{}BetriebsStelleText" minOccurs="0"/>
 *         &lt;element name="Patient" type="{}tpcPerson" minOccurs="0"/>
 *         &lt;element ref="{}Beziehungen" minOccurs="0"/>
 *         &lt;element ref="{}FamilienName" minOccurs="0"/>
 *         &lt;element ref="{}VorName" minOccurs="0"/>
 *         &lt;element ref="{}Geschlecht" minOccurs="0"/>
 *         &lt;element ref="{}GeburtsDatum" minOccurs="0"/>
 *         &lt;element ref="{}SVNummer" minOccurs="0"/>
 *         &lt;element name="AufenthaltsArt" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attGroup ref="{}agrCodeList"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Status" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="aufgenommen"/>
 *               &lt;enumeration value="entlassen"/>
 *               &lt;enumeration value="storniert"/>
 *               &lt;enumeration value="voradministriert"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AufnahmeZeit" type="{}tpsDatumZeitEmpty" minOccurs="0"/>
 *         &lt;element name="AufnahmeArt" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attGroup ref="{}agrCodeList"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntlassungsZeit" type="{}tpsDatumZeitEmpty" minOccurs="0"/>
 *         &lt;element name="EntlassungsArt" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attGroup ref="{}agrCodeList"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AufenthaltsPfad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpcAufenthalt", propOrder = {

})
public class TpcAufenthalt {

    @XmlElement(name = "AufenthaltsKey", required = true)
    protected String aufenthaltsKey;
    @XmlElement(name = "BetriebsStelleKey")
    protected String betriebsStelleKey;
    @XmlElement(name = "BetriebsStelleText")
    protected String betriebsStelleText;
    @XmlElement(name = "Patient")
    protected TpcPerson patient;
    @XmlElement(name = "Beziehungen")
    protected Beziehungen beziehungen;
    @XmlElement(name = "FamilienName")
    protected String familienName;
    @XmlElement(name = "VorName")
    protected String vorName;
    @XmlElement(name = "Geschlecht")
    protected String geschlecht;
    @XmlElement(name = "GeburtsDatum")
    protected String geburtsDatum;
    @XmlElement(name = "SVNummer")
    protected String svNummer;
    @XmlElement(name = "AufenthaltsArt")
    protected TpcAufenthalt.AufenthaltsArt aufenthaltsArt;
    @XmlElement(name = "Status")
    protected String status;
    @XmlList
    @XmlElement(name = "AufnahmeZeit")
    protected List<String> aufnahmeZeit;
    @XmlElement(name = "AufnahmeArt")
    protected TpcAufenthalt.AufnahmeArt aufnahmeArt;
    @XmlList
    @XmlElement(name = "EntlassungsZeit")
    protected List<String> entlassungsZeit;
    @XmlElement(name = "EntlassungsArt")
    protected TpcAufenthalt.EntlassungsArt entlassungsArt;
    @XmlElement(name = "AufenthaltsPfad")
    protected String aufenthaltsPfad;

    /**
     * Gets the value of the aufenthaltsKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAufenthaltsKey() {
        return aufenthaltsKey;
    }

    /**
     * Sets the value of the aufenthaltsKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAufenthaltsKey(String value) {
        this.aufenthaltsKey = value;
    }

    /**
     * Gets the value of the betriebsStelleKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBetriebsStelleKey() {
        return betriebsStelleKey;
    }

    /**
     * Sets the value of the betriebsStelleKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBetriebsStelleKey(String value) {
        this.betriebsStelleKey = value;
    }

    /**
     * Gets the value of the betriebsStelleText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBetriebsStelleText() {
        return betriebsStelleText;
    }

    /**
     * Sets the value of the betriebsStelleText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBetriebsStelleText(String value) {
        this.betriebsStelleText = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link TpcPerson }
     *     
     */
    public TpcPerson getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpcPerson }
     *     
     */
    public void setPatient(TpcPerson value) {
        this.patient = value;
    }

    /**
     * Gets the value of the beziehungen property.
     * 
     * @return
     *     possible object is
     *     {@link Beziehungen }
     *     
     */
    public Beziehungen getBeziehungen() {
        return beziehungen;
    }

    /**
     * Sets the value of the beziehungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Beziehungen }
     *     
     */
    public void setBeziehungen(Beziehungen value) {
        this.beziehungen = value;
    }

    /**
     * Gets the value of the familienName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilienName() {
        return familienName;
    }

    /**
     * Sets the value of the familienName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilienName(String value) {
        this.familienName = value;
    }

    /**
     * Gets the value of the vorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorName() {
        return vorName;
    }

    /**
     * Sets the value of the vorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorName(String value) {
        this.vorName = value;
    }

    /**
     * Gets the value of the geschlecht property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeschlecht() {
        return geschlecht;
    }

    /**
     * Sets the value of the geschlecht property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeschlecht(String value) {
        this.geschlecht = value;
    }

    /**
     * Gets the value of the geburtsDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeburtsDatum() {
        return geburtsDatum;
    }

    /**
     * Sets the value of the geburtsDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeburtsDatum(String value) {
        this.geburtsDatum = value;
    }

    /**
     * Gets the value of the svNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSVNummer() {
        return svNummer;
    }

    /**
     * Sets the value of the svNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSVNummer(String value) {
        this.svNummer = value;
    }

    /**
     * Gets the value of the aufenthaltsArt property.
     * 
     * @return
     *     possible object is
     *     {@link TpcAufenthalt.AufenthaltsArt }
     *     
     */
    public TpcAufenthalt.AufenthaltsArt getAufenthaltsArt() {
        return aufenthaltsArt;
    }

    /**
     * Sets the value of the aufenthaltsArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpcAufenthalt.AufenthaltsArt }
     *     
     */
    public void setAufenthaltsArt(TpcAufenthalt.AufenthaltsArt value) {
        this.aufenthaltsArt = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the aufnahmeZeit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aufnahmeZeit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAufnahmeZeit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAufnahmeZeit() {
        if (aufnahmeZeit == null) {
            aufnahmeZeit = new ArrayList<String>();
        }
        return this.aufnahmeZeit;
    }

    /**
     * Gets the value of the aufnahmeArt property.
     * 
     * @return
     *     possible object is
     *     {@link TpcAufenthalt.AufnahmeArt }
     *     
     */
    public TpcAufenthalt.AufnahmeArt getAufnahmeArt() {
        return aufnahmeArt;
    }

    /**
     * Sets the value of the aufnahmeArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpcAufenthalt.AufnahmeArt }
     *     
     */
    public void setAufnahmeArt(TpcAufenthalt.AufnahmeArt value) {
        this.aufnahmeArt = value;
    }

    /**
     * Gets the value of the entlassungsZeit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entlassungsZeit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntlassungsZeit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEntlassungsZeit() {
        if (entlassungsZeit == null) {
            entlassungsZeit = new ArrayList<String>();
        }
        return this.entlassungsZeit;
    }

    /**
     * Gets the value of the entlassungsArt property.
     * 
     * @return
     *     possible object is
     *     {@link TpcAufenthalt.EntlassungsArt }
     *     
     */
    public TpcAufenthalt.EntlassungsArt getEntlassungsArt() {
        return entlassungsArt;
    }

    /**
     * Sets the value of the entlassungsArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpcAufenthalt.EntlassungsArt }
     *     
     */
    public void setEntlassungsArt(TpcAufenthalt.EntlassungsArt value) {
        this.entlassungsArt = value;
    }

    /**
     * Gets the value of the aufenthaltsPfad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAufenthaltsPfad() {
        return aufenthaltsPfad;
    }

    /**
     * Sets the value of the aufenthaltsPfad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAufenthaltsPfad(String value) {
        this.aufenthaltsPfad = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attGroup ref="{}agrCodeList"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AufenthaltsArt {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Bereich")
        protected String bereich;
        @XmlAttribute(name = "Verzeichnis")
        protected String verzeichnis;
        @XmlAttribute(name = "Code")
        protected String code;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the bereich property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBereich() {
            return bereich;
        }

        /**
         * Sets the value of the bereich property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBereich(String value) {
            this.bereich = value;
        }

        /**
         * Gets the value of the verzeichnis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerzeichnis() {
            return verzeichnis;
        }

        /**
         * Sets the value of the verzeichnis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerzeichnis(String value) {
            this.verzeichnis = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attGroup ref="{}agrCodeList"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AufnahmeArt {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Bereich")
        protected String bereich;
        @XmlAttribute(name = "Verzeichnis")
        protected String verzeichnis;
        @XmlAttribute(name = "Code")
        protected String code;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the bereich property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBereich() {
            return bereich;
        }

        /**
         * Sets the value of the bereich property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBereich(String value) {
            this.bereich = value;
        }

        /**
         * Gets the value of the verzeichnis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerzeichnis() {
            return verzeichnis;
        }

        /**
         * Sets the value of the verzeichnis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerzeichnis(String value) {
            this.verzeichnis = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attGroup ref="{}agrCodeList"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class EntlassungsArt {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Bereich")
        protected String bereich;
        @XmlAttribute(name = "Verzeichnis")
        protected String verzeichnis;
        @XmlAttribute(name = "Code")
        protected String code;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the bereich property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBereich() {
            return bereich;
        }

        /**
         * Sets the value of the bereich property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBereich(String value) {
            this.bereich = value;
        }

        /**
         * Gets the value of the verzeichnis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerzeichnis() {
            return verzeichnis;
        }

        /**
         * Sets the value of the verzeichnis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerzeichnis(String value) {
            this.verzeichnis = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

    }

}
