/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tpcDokument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpcDokument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}DokumentenKey"/>
 *         &lt;element ref="{}AufenthaltsKey"/>
 *         &lt;element ref="{}BetriebsStelleKey"/>
 *         &lt;element ref="{}DVRNummer" minOccurs="0"/>
 *         &lt;element name="DokumentenBesitzer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AenderungsZeit" type="{}tpsDatumZeit" minOccurs="0"/>
 *         &lt;element name="DokumentenUeberschrift" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}DokumentenZeit"/>
 *         &lt;element name="DokumentenStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DokumentenStatusText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Qualifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QualifierText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AnfordererKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AnfordererText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DokumentenPfad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SperrKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpcDokument", propOrder = {

})
public class TpcDokument {

    @XmlElement(name = "DokumentenKey", required = true)
    protected String dokumentenKey;
    @XmlElement(name = "AufenthaltsKey", required = true)
    protected String aufenthaltsKey;
    @XmlElement(name = "BetriebsStelleKey", required = true)
    protected String betriebsStelleKey;
    @XmlElement(name = "DVRNummer")
    protected String dvrNummer;
    @XmlElement(name = "DokumentenBesitzer")
    protected String dokumentenBesitzer;
    @XmlElement(name = "AenderungsZeit")
    protected String aenderungsZeit;
    @XmlElement(name = "DokumentenUeberschrift")
    protected String dokumentenUeberschrift;
    @XmlElement(name = "DokumentenZeit", required = true)
    protected String dokumentenZeit;
    @XmlElement(name = "DokumentenStatus")
    protected String dokumentenStatus;
    @XmlElement(name = "DokumentenStatusText")
    protected String dokumentenStatusText;
    @XmlElement(name = "Qualifier", required = true)
    protected String qualifier;
    @XmlElement(name = "QualifierText", required = true)
    protected String qualifierText;
    @XmlElement(name = "AnfordererKey")
    protected String anfordererKey;
    @XmlElement(name = "AnfordererText")
    protected String anfordererText;
    @XmlElement(name = "DokumentenPfad")
    protected String dokumentenPfad;
    @XmlElement(name = "SperrKey")
    protected String sperrKey;

    /**
     * Gets the value of the dokumentenKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentenKey() {
        return dokumentenKey;
    }

    /**
     * Sets the value of the dokumentenKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentenKey(String value) {
        this.dokumentenKey = value;
    }

    /**
     * Gets the value of the aufenthaltsKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAufenthaltsKey() {
        return aufenthaltsKey;
    }

    /**
     * Sets the value of the aufenthaltsKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAufenthaltsKey(String value) {
        this.aufenthaltsKey = value;
    }

    /**
     * Gets the value of the betriebsStelleKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBetriebsStelleKey() {
        return betriebsStelleKey;
    }

    /**
     * Sets the value of the betriebsStelleKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBetriebsStelleKey(String value) {
        this.betriebsStelleKey = value;
    }

    /**
     * Gets the value of the dvrNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDVRNummer() {
        return dvrNummer;
    }

    /**
     * Sets the value of the dvrNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDVRNummer(String value) {
        this.dvrNummer = value;
    }

    /**
     * Gets the value of the dokumentenBesitzer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentenBesitzer() {
        return dokumentenBesitzer;
    }

    /**
     * Sets the value of the dokumentenBesitzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentenBesitzer(String value) {
        this.dokumentenBesitzer = value;
    }

    /**
     * Gets the value of the aenderungsZeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAenderungsZeit() {
        return aenderungsZeit;
    }

    /**
     * Sets the value of the aenderungsZeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAenderungsZeit(String value) {
        this.aenderungsZeit = value;
    }

    /**
     * Gets the value of the dokumentenUeberschrift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentenUeberschrift() {
        return dokumentenUeberschrift;
    }

    /**
     * Sets the value of the dokumentenUeberschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentenUeberschrift(String value) {
        this.dokumentenUeberschrift = value;
    }

    /**
     * Gets the value of the dokumentenZeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentenZeit() {
        return dokumentenZeit;
    }

    /**
     * Sets the value of the dokumentenZeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentenZeit(String value) {
        this.dokumentenZeit = value;
    }

    /**
     * Gets the value of the dokumentenStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentenStatus() {
        return dokumentenStatus;
    }

    /**
     * Sets the value of the dokumentenStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentenStatus(String value) {
        this.dokumentenStatus = value;
    }

    /**
     * Gets the value of the dokumentenStatusText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentenStatusText() {
        return dokumentenStatusText;
    }

    /**
     * Sets the value of the dokumentenStatusText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentenStatusText(String value) {
        this.dokumentenStatusText = value;
    }

    /**
     * Gets the value of the qualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifier() {
        return qualifier;
    }

    /**
     * Sets the value of the qualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifier(String value) {
        this.qualifier = value;
    }

    /**
     * Gets the value of the qualifierText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifierText() {
        return qualifierText;
    }

    /**
     * Sets the value of the qualifierText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifierText(String value) {
        this.qualifierText = value;
    }

    /**
     * Gets the value of the anfordererKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnfordererKey() {
        return anfordererKey;
    }

    /**
     * Sets the value of the anfordererKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnfordererKey(String value) {
        this.anfordererKey = value;
    }

    /**
     * Gets the value of the anfordererText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnfordererText() {
        return anfordererText;
    }

    /**
     * Sets the value of the anfordererText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnfordererText(String value) {
        this.anfordererText = value;
    }

    /**
     * Gets the value of the dokumentenPfad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentenPfad() {
        return dokumentenPfad;
    }

    /**
     * Sets the value of the dokumentenPfad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentenPfad(String value) {
        this.dokumentenPfad = value;
    }

    /**
     * Gets the value of the sperrKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSperrKey() {
        return sperrKey;
    }

    /**
     * Sets the value of the sperrKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSperrKey(String value) {
        this.sperrKey = value;
    }

}
