/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for tpcPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpcPerson">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}FamilienName"/>
 *         &lt;element ref="{}VorName"/>
 *         &lt;element ref="{}Titel" minOccurs="0"/>
 *         &lt;element ref="{}GeburtsDatum" minOccurs="0"/>
 *         &lt;element ref="{}Geschlecht" minOccurs="0"/>
 *         &lt;element ref="{}eMail" minOccurs="0"/>
 *         &lt;element ref="{}Rollen" minOccurs="0"/>
 *         &lt;element ref="{}PublicCertificateKey" minOccurs="0"/>
 *         &lt;element ref="{}Kommunikation" minOccurs="0"/>
 *         &lt;element ref="{}Identifikationen" minOccurs="0"/>
 *         &lt;element ref="{}GeburtsName" minOccurs="0"/>
 *         &lt;element name="SterbeDatum" type="{}tpsDatumZeit" minOccurs="0"/>
 *         &lt;element name="StaatsBuergerschaft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FamilienStand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}Adresse" minOccurs="0"/>
 *         &lt;element name="PfadDerAufenthalte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}Beziehungen" minOccurs="0"/>
 *         &lt;element name="AusuebenderBeruf" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attGroup ref="{}agrCodeList"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpcPerson", propOrder = {

})
@XmlSeeAlso({
    Beziehungen.Person.class
})
public class TpcPerson {

    @XmlElement(name = "FamilienName", required = true)
    protected String familienName;
    @XmlElement(name = "VorName", required = true)
    protected String vorName;
    @XmlElement(name = "Titel")
    protected String titel;
    @XmlElement(name = "GeburtsDatum")
    protected String geburtsDatum;
    @XmlElement(name = "Geschlecht")
    protected String geschlecht;
    protected String eMail;
    @XmlElement(name = "Rollen")
    protected Rollen rollen;
    @XmlElement(name = "PublicCertificateKey")
    protected String publicCertificateKey;
    @XmlElement(name = "Kommunikation")
    protected Kommunikation kommunikation;
    @XmlElement(name = "Identifikationen")
    protected Identifikationen identifikationen;
    @XmlElement(name = "GeburtsName")
    protected String geburtsName;
    @XmlElement(name = "SterbeDatum")
    protected String sterbeDatum;
    @XmlElement(name = "StaatsBuergerschaft")
    protected String staatsBuergerschaft;
    @XmlElement(name = "FamilienStand")
    protected String familienStand;
    @XmlElement(name = "Adresse")
    protected TpcAdresse adresse;
    @XmlElement(name = "PfadDerAufenthalte")
    protected String pfadDerAufenthalte;
    @XmlElement(name = "Beziehungen")
    protected Beziehungen beziehungen;
    @XmlElement(name = "AusuebenderBeruf")
    protected TpcPerson.AusuebenderBeruf ausuebenderBeruf;

    /**
     * Gets the value of the familienName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilienName() {
        return familienName;
    }

    /**
     * Sets the value of the familienName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilienName(String value) {
        this.familienName = value;
    }

    /**
     * Gets the value of the vorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorName() {
        return vorName;
    }

    /**
     * Sets the value of the vorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorName(String value) {
        this.vorName = value;
    }

    /**
     * Gets the value of the titel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the geburtsDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeburtsDatum() {
        return geburtsDatum;
    }

    /**
     * Sets the value of the geburtsDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeburtsDatum(String value) {
        this.geburtsDatum = value;
    }

    /**
     * Gets the value of the geschlecht property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeschlecht() {
        return geschlecht;
    }

    /**
     * Sets the value of the geschlecht property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeschlecht(String value) {
        this.geschlecht = value;
    }

    /**
     * Gets the value of the eMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMail() {
        return eMail;
    }

    /**
     * Sets the value of the eMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMail(String value) {
        this.eMail = value;
    }

    /**
     * Gets the value of the rollen property.
     * 
     * @return
     *     possible object is
     *     {@link Rollen }
     *     
     */
    public Rollen getRollen() {
        return rollen;
    }

    /**
     * Sets the value of the rollen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rollen }
     *     
     */
    public void setRollen(Rollen value) {
        this.rollen = value;
    }

    /**
     * Gets the value of the publicCertificateKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicCertificateKey() {
        return publicCertificateKey;
    }

    /**
     * Sets the value of the publicCertificateKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicCertificateKey(String value) {
        this.publicCertificateKey = value;
    }

    /**
     * Gets the value of the kommunikation property.
     * 
     * @return
     *     possible object is
     *     {@link Kommunikation }
     *     
     */
    public Kommunikation getKommunikation() {
        return kommunikation;
    }

    /**
     * Sets the value of the kommunikation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kommunikation }
     *     
     */
    public void setKommunikation(Kommunikation value) {
        this.kommunikation = value;
    }

    /**
     * Gets the value of the identifikationen property.
     * 
     * @return
     *     possible object is
     *     {@link Identifikationen }
     *     
     */
    public Identifikationen getIdentifikationen() {
        return identifikationen;
    }

    /**
     * Sets the value of the identifikationen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifikationen }
     *     
     */
    public void setIdentifikationen(Identifikationen value) {
        this.identifikationen = value;
    }

    /**
     * Gets the value of the geburtsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeburtsName() {
        return geburtsName;
    }

    /**
     * Sets the value of the geburtsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeburtsName(String value) {
        this.geburtsName = value;
    }

    /**
     * Gets the value of the sterbeDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSterbeDatum() {
        return sterbeDatum;
    }

    /**
     * Sets the value of the sterbeDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSterbeDatum(String value) {
        this.sterbeDatum = value;
    }

    /**
     * Gets the value of the staatsBuergerschaft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaatsBuergerschaft() {
        return staatsBuergerschaft;
    }

    /**
     * Sets the value of the staatsBuergerschaft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaatsBuergerschaft(String value) {
        this.staatsBuergerschaft = value;
    }

    /**
     * Gets the value of the familienStand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilienStand() {
        return familienStand;
    }

    /**
     * Sets the value of the familienStand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilienStand(String value) {
        this.familienStand = value;
    }

    /**
     * Gets the value of the adresse property.
     * 
     * @return
     *     possible object is
     *     {@link TpcAdresse }
     *     
     */
    public TpcAdresse getAdresse() {
        return adresse;
    }

    /**
     * Sets the value of the adresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpcAdresse }
     *     
     */
    public void setAdresse(TpcAdresse value) {
        this.adresse = value;
    }

    /**
     * Gets the value of the pfadDerAufenthalte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPfadDerAufenthalte() {
        return pfadDerAufenthalte;
    }

    /**
     * Sets the value of the pfadDerAufenthalte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPfadDerAufenthalte(String value) {
        this.pfadDerAufenthalte = value;
    }

    /**
     * Gets the value of the beziehungen property.
     * 
     * @return
     *     possible object is
     *     {@link Beziehungen }
     *     
     */
    public Beziehungen getBeziehungen() {
        return beziehungen;
    }

    /**
     * Sets the value of the beziehungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Beziehungen }
     *     
     */
    public void setBeziehungen(Beziehungen value) {
        this.beziehungen = value;
    }

    /**
     * Gets the value of the ausuebenderBeruf property.
     * 
     * @return
     *     possible object is
     *     {@link TpcPerson.AusuebenderBeruf }
     *     
     */
    public TpcPerson.AusuebenderBeruf getAusuebenderBeruf() {
        return ausuebenderBeruf;
    }

    /**
     * Sets the value of the ausuebenderBeruf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpcPerson.AusuebenderBeruf }
     *     
     */
    public void setAusuebenderBeruf(TpcPerson.AusuebenderBeruf value) {
        this.ausuebenderBeruf = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attGroup ref="{}agrCodeList"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AusuebenderBeruf {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Bereich")
        protected String bereich;
        @XmlAttribute(name = "Verzeichnis")
        protected String verzeichnis;
        @XmlAttribute(name = "Code")
        protected String code;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the bereich property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBereich() {
            return bereich;
        }

        /**
         * Sets the value of the bereich property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBereich(String value) {
            this.bereich = value;
        }

        /**
         * Gets the value of the verzeichnis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerzeichnis() {
            return verzeichnis;
        }

        /**
         * Sets the value of the verzeichnis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerzeichnis(String value) {
            this.verzeichnis = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

    }

}
