/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tpsAntwortVerhalten.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tpsAntwortVerhalten">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ErwartetKeineOrgBestaetigung"/>
 *     &lt;enumeration value="ErwartetKeineTechnBestaetigung"/>
 *     &lt;enumeration value="ErwartetOrgBestaetigung"/>
 *     &lt;enumeration value="ErwartetTechnBestaetigung"/>
 *     &lt;enumeration value="SendetKeineOrgBestaetigung"/>
 *     &lt;enumeration value="SendetKeineTechnBestaetigung"/>
 *     &lt;enumeration value="SendetOrgBestaetigung"/>
 *     &lt;enumeration value="SendetTechnBestaetigung"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tpsAntwortVerhalten")
@XmlEnum
public enum TpsAntwortVerhalten {

    @XmlEnumValue("ErwartetKeineOrgBestaetigung")
    ERWARTET_KEINE_ORG_BESTAETIGUNG("ErwartetKeineOrgBestaetigung"),
    @XmlEnumValue("ErwartetKeineTechnBestaetigung")
    ERWARTET_KEINE_TECHN_BESTAETIGUNG("ErwartetKeineTechnBestaetigung"),
    @XmlEnumValue("ErwartetOrgBestaetigung")
    ERWARTET_ORG_BESTAETIGUNG("ErwartetOrgBestaetigung"),
    @XmlEnumValue("ErwartetTechnBestaetigung")
    ERWARTET_TECHN_BESTAETIGUNG("ErwartetTechnBestaetigung"),
    @XmlEnumValue("SendetKeineOrgBestaetigung")
    SENDET_KEINE_ORG_BESTAETIGUNG("SendetKeineOrgBestaetigung"),
    @XmlEnumValue("SendetKeineTechnBestaetigung")
    SENDET_KEINE_TECHN_BESTAETIGUNG("SendetKeineTechnBestaetigung"),
    @XmlEnumValue("SendetOrgBestaetigung")
    SENDET_ORG_BESTAETIGUNG("SendetOrgBestaetigung"),
    @XmlEnumValue("SendetTechnBestaetigung")
    SENDET_TECHN_BESTAETIGUNG("SendetTechnBestaetigung");
    private final String value;

    TpsAntwortVerhalten(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TpsAntwortVerhalten fromValue(String v) {
        for (TpsAntwortVerhalten c: TpsAntwortVerhalten.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
