/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tpsBefundTransportProvider.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tpsBefundTransportProvider">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AekVbgGNV"/>
 *     &lt;enumeration value="DataKomDame"/>
 *     &lt;enumeration value="MedComMedWare"/>
 *     &lt;enumeration value="MedicalNetConnect2"/>
 *     &lt;enumeration value="MedicalNetSMIME"/>
 *     &lt;enumeration value="MedicalNetWindows"/>
 *     &lt;enumeration value="WienKomMediKom"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tpsBefundTransportProvider")
@XmlEnum
public enum TpsBefundTransportProvider {

    @XmlEnumValue("AekVbgGNV")
    AEK_VBG_GNV("AekVbgGNV"),
    @XmlEnumValue("DataKomDame")
    DATA_KOM_DAME("DataKomDame"),
    @XmlEnumValue("MedComMedWare")
    MED_COM_MED_WARE("MedComMedWare"),
    @XmlEnumValue("MedicalNetConnect2")
    MEDICAL_NET_CONNECT_2("MedicalNetConnect2"),
    @XmlEnumValue("MedicalNetSMIME")
    MEDICAL_NET_SMIME("MedicalNetSMIME"),
    @XmlEnumValue("MedicalNetWindows")
    MEDICAL_NET_WINDOWS("MedicalNetWindows"),
    @XmlEnumValue("WienKomMediKom")
    WIEN_KOM_MEDI_KOM("WienKomMediKom");
    private final String value;

    TpsBefundTransportProvider(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TpsBefundTransportProvider fromValue(String v) {
        for (TpsBefundTransportProvider c: TpsBefundTransportProvider.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
