/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NettoBasisBetrag"/>
 *         &lt;element ref="{}UmsatzsteuerSL"/>
 *         &lt;element ref="{}UmsatzsteuerBetrag"/>
 *         &lt;element ref="{}BruttoBetragMitUmsatzsteuer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nettoBasisBetrag",
    "umsatzsteuerSL",
    "umsatzsteuerBetrag",
    "bruttoBetragMitUmsatzsteuer"
})
@XmlRootElement(name = "UmsatzsteuerBerechnung")
public class UmsatzsteuerBerechnung {

    @XmlElement(name = "NettoBasisBetrag", required = true)
    protected BigDecimal nettoBasisBetrag;
    @XmlElement(name = "UmsatzsteuerSL", required = true)
    protected String umsatzsteuerSL;
    @XmlElement(name = "UmsatzsteuerBetrag", required = true)
    protected BigDecimal umsatzsteuerBetrag;
    @XmlElement(name = "BruttoBetragMitUmsatzsteuer", required = true)
    protected BigDecimal bruttoBetragMitUmsatzsteuer;

    /**
     * Gets the value of the nettoBasisBetrag property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNettoBasisBetrag() {
        return nettoBasisBetrag;
    }

    /**
     * Sets the value of the nettoBasisBetrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNettoBasisBetrag(BigDecimal value) {
        this.nettoBasisBetrag = value;
    }

    /**
     * Gets the value of the umsatzsteuerSL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmsatzsteuerSL() {
        return umsatzsteuerSL;
    }

    /**
     * Sets the value of the umsatzsteuerSL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmsatzsteuerSL(String value) {
        this.umsatzsteuerSL = value;
    }

    /**
     * Gets the value of the umsatzsteuerBetrag property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUmsatzsteuerBetrag() {
        return umsatzsteuerBetrag;
    }

    /**
     * Sets the value of the umsatzsteuerBetrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUmsatzsteuerBetrag(BigDecimal value) {
        this.umsatzsteuerBetrag = value;
    }

    /**
     * Gets the value of the bruttoBetragMitUmsatzsteuer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBruttoBetragMitUmsatzsteuer() {
        return bruttoBetragMitUmsatzsteuer;
    }

    /**
     * Sets the value of the bruttoBetragMitUmsatzsteuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBruttoBetragMitUmsatzsteuer(BigDecimal value) {
        this.bruttoBetragMitUmsatzsteuer = value;
    }

}
