/*******************************************************************************
 * Copyright (c) 2015 MEDEVIT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MEDEVIT <office@medevit.at> - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 11:02:34 AM MESZ 
//


package at.medevit.elexis.kassen.edivka.rechnung.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}UnterbringungsKlasseCode"/>
 *         &lt;element ref="{}UnterbringungsKlasseBezeichnung"/>
 *         &lt;element ref="{}FreiText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unterbringungsKlasseCode",
    "unterbringungsKlasseBezeichnung",
    "freiText"
})
@XmlRootElement(name = "Unterbringung")
public class Unterbringung {

    @XmlElement(name = "UnterbringungsKlasseCode", required = true)
    protected String unterbringungsKlasseCode;
    @XmlElement(name = "UnterbringungsKlasseBezeichnung", required = true)
    protected String unterbringungsKlasseBezeichnung;
    @XmlElement(name = "FreiText")
    protected String freiText;

    /**
     * Gets the value of the unterbringungsKlasseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnterbringungsKlasseCode() {
        return unterbringungsKlasseCode;
    }

    /**
     * Sets the value of the unterbringungsKlasseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnterbringungsKlasseCode(String value) {
        this.unterbringungsKlasseCode = value;
    }

    /**
     * Gets the value of the unterbringungsKlasseBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnterbringungsKlasseBezeichnung() {
        return unterbringungsKlasseBezeichnung;
    }

    /**
     * Sets the value of the unterbringungsKlasseBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnterbringungsKlasseBezeichnung(String value) {
        this.unterbringungsKlasseBezeichnung = value;
    }

    /**
     * Gets the value of the freiText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreiText() {
        return freiText;
    }

    /**
     * Sets the value of the freiText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreiText(String value) {
        this.freiText = value;
    }

}
